# flake8: noqa
config.platform.peakcpus = 120
config.platform.peakmemory = 491520
config.platform.defaultRoot = "/usr"
config.platform.localScratch = "./tests/condor_scratch_slurm"
config.platform.dataDirectory = "/tmp/data_slurm"
config.platform.fileSystemDomain = "lsstcorp.org"
config.platform.eupsPath = "/var/tmp"
config.platform.scheduler = "slurm"
config.platform.setup_using = "getenv"
config.platform.manager = "dagman"
